case $1 in
  wine-10.*|wine-11.*)
    export patchFileArry=(
      path-patch-universal.mylatepatch
      protonoverride2_10.16+.mylatepatch
      termux-wine-fix2.mylatepatch
      wine_virtual_memory2.mylatepatch
    )
    ;;
esac
