case $1 in
  proton-wine-10.0-*)
    export patchFileArry=(
      esync2.patch
      fsync.patch
      path-patch-universal.patch
      proton_virtual_memory_fix2.patch
      unixlib.patch
    )
    ;;
esac
